# --- Theme ---
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# --- Site ---
locale: "ko-KR"
title: "말해지지 않은 것들"
title_separator: "-"
subtitle: "역사 속 인물과 서사를 기록하는 아카이브"
name: "초부"
description: "역사 인물 연구와 창작 아이디어를 기록하는 개인 아카이브 블로그"

# 프로젝트 사이트(서브경로 배포)
url: "https://realworldplay.github.io"
baseurl: "/exrealworldplay.github"

# 컬렉션 경로 깔끔하게
permalink: /:collection/:path/
timezone: "Asia/Seoul"

# --- Collections ---
collections:
  history:
    output: true
  fandom:
    output: true
  newsletter:
    output: true
  columns:
    output: true
  notes:
    output: true
  fieldtrip:
    output: true
  sources:
    output: true
  curation:
    output: true

# --- Defaults (레이아웃/옵션 기본값) ---
defaults:
  - scope:
      path: ""
      type: history
    values:
      layout: single
  - scope:
      path: ""
      type: fandom
    values:
      layout: single
  - scope:
      path: ""
      type: newsletter
    values:
      layout: single
  - scope:
      path: ""
      type: columns
    values:
      layout: single
  - scope:
      path: ""
      type: notes
    values:
      layout: single
  - scope:
      path: ""
      type: fieldtrip
    values:
      layout: single
  - scope:
      path: ""
      type: sources
    values:
      layout: single
  - scope:
      path: ""
      type: curation
    values:
      layout: single
  # posts가 있다면 유지, 없으면 삭제해도 됨
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

# --- Repo/Assets (필요 시 채우기) ---
repository:
teaser:
logo:
masthead_title:
breadcrumbs:
words_per_minute: 200
enable_copy_code_button:

# --- Comments (원하면 하나만 설정) ---
comments:
  provider:

# --- Search/SEO (원하면 켜기) ---
search: true
search_full_content: false
search_provider: lunr
google_site_verification:
bing_site_verification:
naver_site_verification:

# --- Social / Open Graph (원하면 채우기) ---
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:
social:
  type: Person
  name: "초부"
  links: []

# --- Analytics (원하면 채우기) ---
analytics:
  provider:
  google:
    tracking_id:
    anonymize_ip:

# --- Author Card ---
author:
  name: "초부"
  avatar:
  bio: "말하지 못한 감정을 복원하는 감정선해석가"
  location: "하얀탑 뒷골목"
  email:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "Website"
      icon: "fas fa-fw fa-link"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"

# --- Footer ---
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
  since: "2013"

# --- Build ---
include:
  - .htaccess
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# --- Conversion ---
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# --- Kramdown ---
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# --- Sass ---
sass:
  sass_dir: _sass
  style: compressed

# --- Archives (카테고리/태그 페이지 필요 시 유지) ---
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# --- HTML 압축 ---
compress_html:
  clippings: all
  ignore:
    envs: development

# --- Plugins (GitHub Pages 호환) ---
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
